# Generated by Django 4.2.8 on 2023-12-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='nr_of_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='time_of_game',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
